name: GRAPE
version: "4.9.1"
license: "Apache-2.0 AND GPL-2.0-or-later"
date: 2024-08-30
description: |
    GRaph Algorithms using PErmutation groups

authors:
    - name: Leonard H. Soicher
      url: https://webspace.maths.qmul.ac.uk/l.h.soicher/

maintainers:
    - name: Leonard H. Soicher
      url: https://webspace.maths.qmul.ac.uk/l.h.soicher/

GAP: ">=4.11"

www: https://gap-packages.github.io/grape
readme: README.md
packageinfo: https://gap-packages.github.io/grape/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/grape/releases/download/v4.9.1/grape-4.9.1.tar.gz

abstract: |
    <span class="pkgname">GRAPE</span> is a package for computing with graphs and groups, and is primarily designed for constructing and analysing graphs related to groups, finite geometries, and designs.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    graph, geometry, design.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Soi24</span>]   <b class='BibAuthor'>Soicher, L. H.</b>,
     <i class='BibTitle'>GRAPE, GRaph Algorithms using PErmutation groups,
             Version 4.9.1</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/grape">https://gap-packages.github.io/grape</a></span>.
    </p>
    

bibtex: |
    @misc{ GRAPE,
      author =           {Soicher, L. H.},
      title =            {{GRAPE},  GRaph  Algorithms  using PErmutation groups,
                          {V}ersion 4.9.1},
      month =            {Aug},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/grape}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{grape}}},
      keywords =         {graph; geometry; design},
      printedkey =       {Soi24}
    }

