name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: "${{ matrix.os }} ${{ matrix.ABI }}-bit / ${{ matrix.engine }} / GAP ${{ matrix.gap-branch }}"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        gap-branch:
          - master
          - stable-4.15
          - stable-4.14
          - stable-4.13
          - stable-4.12
          - stable-4.11
        ABI:
          - 64
        engine:
          - nauty

        include:
          - gap-branch: master
            ABI: 32
            engine: nauty
            os: ubuntu
          - gap-branch: master
            ABI: 64
            engine: bliss
            os: ubuntu
          - gap-branch: master
            ABI: 64
            engine: nauty
            os: windows

    env:
      GRAPE_NAUTY: ${{ matrix.engine == 'nauty' }}

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-cygwin@v2
        if: ${{ runner.os == 'Windows' }}
      - name: "Install bliss"
        if: ${{ matrix.engine == 'bliss' }}
        run: sudo apt-get install bliss
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
          #GAP_PKGS_TO_BUILD: 'profiling io' # done by setup-gap@v2
      - uses: gap-actions/build-pkg@v2
      - uses: gap-actions/run-pkg-tests@v4
      - uses: gap-actions/run-pkg-tests@v4
        with:
          only-needed: true
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: ./doc/manual.pdf
          if-no-files-found: error
